---
- hosts: all
  connection: httpapi
  gather_facts: false
  pre_tasks:
  - name : Install Collections dependencies
    shell: ansible-galaxy install -r collections/requirements.yaml
    delegate_to: 127.0.0.1
      
  tasks:
  - name: show-access-rulebase
    check_point.mgmt.cp_mgmt_access_rule_facts:
      details_level: standard
      name: Network
    ignore_errors: true
