---
- hosts: all
  connection: local
  gather_facts: false
  pre_tasks:
  - name : Install Collections dependencies
    shell: ansible-galaxy install -r collections/requirements.yaml
    delegate_to: 127.0.0.1
      
  tasks:
  - name: show network facts
    check_point.mgmt.cp_mgmt_network_facts:
    ignore_errors: true

  - name: show-access-rulebase
    check_point.mgmt.cp_mgmt_access_rule_facts:
      details_level: standard
      limit: 20
      name: Network
      offset: 0
      use_object_dictionary: true
    ignore_errors: true

  - shell: |
      ansible-galaxy collection list
    delegate_to: localhost

