---
- name: set vars
  hosts: localhost
  gather_facts: false
  pre_tasks:
  - name : Install Collections dependencies
    shell: ansible-galaxy install -r collections/requirements.yaml
    delegate_to: 127.0.0.1
  tasks: 
  - name: set MDS and CMA IPs
    set_fact:
      g_mds_ip: "10.70.32.25"
      g_cma_ip: "10.70.32.26"
- name: work on CMA
  hosts: "{{ hostvars['localhost']['g_cma_ip'] }}"
  connection: httpapi
  gather_facts: false
  tasks:
  - name: show api versions
    check_point.mgmt.cp_mgmt_show_api_versions:
  - name: show-access-layers
    check_point.mgmt.cp_mgmt_access_layer_facts:
      details_level: standard
      limit: 50
      offset: 0
  - name: show-access-rulebase
    check_point.mgmt.cp_mgmt_access_rule_facts:
      details_level: standard
      # layer: Network
      name: Network
      offset: 0
      limit: 50
      use_object_dictionary: true
      version: 1.7
    ignore_errors: true  
#  - name: add SMTP rule
#    check_point.mgmt.cp_mgmt_access_rule:
#      auto_publish_session: true
#      action: "Accept"
