---
- name: set vars
  hosts: localhost
  gather_facts: false
  pre_tasks:
  - name : Install Collections dependencies
    shell: ansible-galaxy install -r collections/requirements.yaml
    delegate_to: 127.0.0.1
  tasks: 
  - name: set MDS IP
    set_fact:
      g_mds_ip: "10.70.32.25"
  - name: set CMA IP
    set_fact:
      g_cma_ip: "10.70.32.26"
- name: work on CMA
  hosts: "{{ hostvars['localhost']['g_cma_ip'] }}"
  gather_facts: false
  tasks:
  - name: show-access-rulebase
    check_point.mgmt.cp_mgmt_access_rule_facts:
      details_level: standard
      limit: 20
      name: Network
      offset: 0
      use_object_dictionary: true
    ignore_errors: true  
  - name: add SMTP rule
    check_point.mgmt.cp_mgmt_access_rule:
      auto_publish_session: true
      action: "Accept"
